
[install]
#boot_iso_url = "https://archive.org/download/Windows7-iso/win7_64_bit.iso"
#boot_iso = "/mnt/scratch/vms/win7_64_bit.iso"

#boot_iso_url = "https://archive.org/download/tiny-10-NTDEV/Tiny10%20B4%20x64.iso"
#boot_iso = "/mnt/scratch/vms/tiny10-b4-x64.iso"
boot_iso_url = ""
boot_iso = "/mnt/scratch/vms/Tiny10 B4 x64.iso"


[vm]
name = "League-Tiny10"
mount_windows_virtio_iso = true
disk_image = "/mnt/scratch/vms/league-tiny10.qcow2"
disk_image_gb = 146
ram_mb = 9096



