
[install]
boot_iso_url = "https://archive.org/download/tiny-11-NTDEV/tiny11a64%20r1.iso"
boot_iso = "/mnt/scratch/vms/tiny11-b1.iso"

[vm]
name = "Tiny11"
mount_windows_virtio_iso = true
disk_image = "/mnt/scratch/vms/tiny11.qcow2"
disk_image_gb = 32
ram_mb = 8096



