
[install]
boot_iso = "/mnt/scratch/vms/Win11_23H2_English_x64v2.iso"


[vm]
name = "Windows-SSK-SSD"
mount_windows_virtio_iso = true
disk_partuuid = "e37867c5-1e8a-41e6-8877-d337cb7ed435" # Looked up + the disk holding this partition is what's booted; ie blkid /dev/sda1
ram_mb = 18128
#ram_mb = 26256

# windows 10/11 wants a BIOS declaring support for secure boot; when empty we can specify details in addtl_args[]
# bios_override = "/usr/share/edk2-ovmf/x64/OVMF_CODE.secboot.fd"
bios_override = ""

# Needs to be "off" if we're using GTK GUI w/ "-disply gtk"
# spice_gl_override = "off"

smp_override = "8"


# Appended to qemu command
addtl_args = [

# This is necessary for some boot magic w/ modern EFI
  "-machine", "q35",

# Temporary install media
#   "-boot", "d", "-drive", "file=/mnt/scratch/vms/Win11_23H2_English_x64v2.iso,media=cdrom,readonly=on",
#   "-display", "gtk",

  "-device", "qemu-xhci",

  "-drive", "if=pflash,format=raw,readonly=on,file=/usr/share/edk2-ovmf/x64/OVMF_CODE.secboot.fd",
# Remember to run:
#    cp /usr/share/edk2-ovmf/x64/OVMF_VARS.fd /tmp/
  "-drive", "if=pflash,format=raw,file=/tmp/OVMF_VARS.fd",

# These require inputs provided by preboot_cmds below
  "-chardev", "socket,id=chrtpm,path=/tmp/tpm/swtpm-sock",
  "-tpmdev", "emulator,id=tpm0,chardev=chrtpm",
  "-device", "tpm-tis,tpmdev=tpm0",

]

rdp_uname = "jeffrey"
rdp_pass = "Passw0rd!"

addtl_rdp_args = [
  # Run 'sudo opensc-tool --list-readers' for names
  #"/smartcard:Alcor Micro AU9540 00 00",
  "/smartcard:Alcor Link AK9563 00 00",

  # "/rfx",

]


# Every one of these is passed in-order to /bin/sh -c "VALUE"
# For this particular VM, they handle the secure-boot and TPMv2 virtualization stuff win11 wants.
preboot_cmds = [
  # "sudo modprobe qxl",
  "mkdir -p /tmp/tpm",
  "cp /usr/share/edk2-ovmf/x64/OVMF_VARS.fd /tmp/",
  "swtpm socket --tpm2 --tpmstate dir=/tmp/tpm --ctrl type=unixio,path=/tmp/tpm/swtpm-sock",
]

