
[install]
boot_iso = "/mnt/scratch/vms/Win10_22H2_English_x64v1.iso"


[vm]
name = "League-Win10"
mount_windows_virtio_iso = true
# disk_image = "/mnt/scratch/vms/league-win10.qcow2"
# disk_image_gb = 146
disk_partuuid = "f26e2d08-0f10-11ee-b535-525400123456" # Looked up + the disk holding this partition is what's booted.
ram_mb = 18128
#ram_mb = 26256

# windows 10/11 wants a BIOS declaring support for secure boot
# bios_override = "/usr/share/edk2-ovmf/x64/OVMF_CODE.secboot.fd"
bios_override = ""

# Needs to be "off" if we're using GTK GUI w/ "-disply gtk"
# spice_gl_override = "off"

smp_override = "8"


# Appended to qemu command
addtl_args = [
  "-device", "qemu-xhci",

  "-drive", "if=pflash,format=raw,readonly=on,file=/usr/share/edk2-ovmf/x64/OVMF_CODE.secboot.fd",
# Remember to run:
#    cp /usr/share/edk2-ovmf/x64/OVMF_VARS.fd /tmp/
  "-drive", "if=pflash,format=raw,file=/tmp/OVMF_VARS.fd",

#  "-vga", "std",
#  "-display", "gtk",

  # "-global", "ICH9-LPC.disable_s3=1",


# Remember to run
#   yay -S swtpm
#   mkdir -p /tmp/tpm
#   swtpm socket --tpm2 --tpmstate dir="/tmp/tpm" --ctrl type=unixio,path="/tmp/tpm/swtpm-sock"
#       while true ; do swtpm socket --tpm2 --tpmstate dir="/tmp/tpm" --ctrl type=unixio,path="/tmp/tpm/swtpm-sock" ; done
  "-chardev", "socket,id=chrtpm,path=/tmp/tpm/swtpm-sock",
  "-tpmdev", "emulator,id=tpm0,chardev=chrtpm",
  "-device", "tpm-tis,tpmdev=tpm0",

]

rdp_uname = "jeffrey"
rdp_pass = "Passw0rd!"

addtl_rdp_args = [
  # Run 'sudo opensc-tool --list-readers' for names
  #"/smartcard:Alcor Micro AU9540 00 00",
  "/smartcard:Alcor Link AK9563 00 00",

  "/rfx",

]


# Every one of these is passed in-order to /bin/sh -c "VALUE"
# For this particular VM, they handle the secure-boot and TPMv2 virtualization stuff win11 wants.
preboot_cmds = [
  "mkdir -p /tmp/tpm",
  "cp /usr/share/edk2-ovmf/x64/OVMF_VARS.fd /tmp/",
  "swtpm socket --tpm2 --tpmstate dir=/tmp/tpm --ctrl type=unixio,path=/tmp/tpm/swtpm-sock",
]

