
[install]
boot_iso = "/mnt/scratch/vms/Win10_22H2_English_x64v1.iso"


[vm]
name = "League-Win10"
mount_windows_virtio_iso = true
# disk_image = "/mnt/scratch/vms/league-win10.qcow2"
# disk_image_gb = 146
disk_partuuid = "f26e2d08-0f10-11ee-b535-525400123456" # Looked up + the disk holding this partition is what's booted.
ram_mb = 9696
#ram_mb = 26256

# Appended to qemu command
addtl_args = [
  "-device", "qemu-xhci",
]


rdp_uname = "jeffrey"
rdp_pass = "Passw0rd!"

addtl_rdp_args = [
  "/smartcard:Alcor Micro AU9540 00 00",
]


