
[install]
boot_iso = "/mnt/scratch/vms/Win10_22H2_English_x64v1.iso"


[vm]
name = "League-Win10"
mount_windows_virtio_iso = true
# disk_image = "/mnt/scratch/vms/league-win10.qcow2"
# disk_image_gb = 146
disk_partuuid = "f26e2d08-0f10-11ee-b535-525400123456" # Looked up + the disk holding this partition is what's booted.
ram_mb = 18128
#ram_mb = 26256

# windows 10/11 wants a BIOS declaring support for secure boot
bios_override = "/usr/share/OVMF/x64/OVMF_CODE.secboot.fd"

# Appended to qemu command
addtl_args = [
  "-device", "qemu-xhci",
  # From 'in-out-differ lsusb': Bus 003 Device 012: ID 04e6:5116 SCM Microsystems, Inc. SCR331-LC1 / SCR3310 SmartCard Reader
  #"-usb", "-device", "usb-host,hostbus=003,hostaddr=012"
  # "-usb", "-device", "usb-host,vendorid=0x04e6,productid=0x5116"
]


rdp_uname = "jeffrey"
rdp_pass = "Passw0rd!"

addtl_rdp_args = [
  # Run 'sudo opensc-tool --list-readers' for names
  #"/smartcard:Alcor Micro AU9540 00 00",
  "/smartcard:Alcor Link AK9563 00 00",
]


